export const projects = [
    {
        id: 1,
        name: 'Project Alpha',
        department: 'HR',
        accessLevel: 3,
        team: [1,2],
        description: 'A project about alpha testing.',
        startDate: '2023-01-01',
        endDate: '2023-12-31',
        status: 'ongoing',
        budget: 100000,
        teamMembers: ['Alice', 'Bob'],
    },
    {
        id: 2,
        name: 'Project Beta',
        department: 'IT',
        accessLevel: 2,
        team: [3,4],
        description: 'A project about beta testing.',
        startDate: '2023-02-01',
        endDate: '2023-11-30',
        status: 'completed',
        budget: 200000,
        teamMembers: ['Charlie', 'Dave'],
    },
]